spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:evcsm_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop