# Project configuration
server:
  port: 2022
  error:
    include-message: always
    include-binding-errors: always
# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/kotlin-spring-db
    username: sa
    password:
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop